# Generated by Django 3.0 on 2020-11-04 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street')),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=14, null=True, verbose_name='Fax')),
                ('is_shipping_address', models.BooleanField(default=False, verbose_name='Is Shipping Address')),
                ('is_Billing_address', models.BooleanField(default=False, verbose_name='Is Billing Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': "Address's",
            },
        ),
    ]
