# Generated by Django 3.0 on 2020-11-03 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Variant Name')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100, verbose_name='Variant Detail')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.Variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'VariantOption',
                'verbose_name_plural': 'VariantOptions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('model', models.CharField(max_length=50, verbose_name='Model Name')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('barcode', models.CharField(max_length=50, verbose_name='Barcode')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Current Quantity')),
                ('height', models.FloatField(default=0, verbose_name='Height')),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
                ('vat', models.FloatField(verbose_name='Value-Added Tax')),
                ('starting_balance', models.IntegerField(verbose_name='Starting Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='IsActive')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('plan', models.CharField(choices=[('quantity', 'Quantity'), ('sub_total', 'Total')], default='quantity', max_length=10, verbose_name='Offer Plan')),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Offer Target')),
                ('offer_type', models.CharField(choices=[('gift', 'Gift'), ('valued_discount', 'Value'), ('percentage_discount', 'Percentage')], default='gift', max_length=20, verbose_name='Target Type')),
                ('offer_times', models.CharField(choices=[('ONCE', 'Apply offer one time per order'), ('FOREACH', "Each time customer reach's the target Apply Offer"), ('FOR_X', 'Apply offer for X times on the same order'), ('LIMITED', 'Apply offer once per order for X times')], default='ONCE', max_length=50, verbose_name='Target Type')),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Reward')),
                ('offer_max_times', models.PositiveIntegerField(default=0, verbose_name='Offer Limit')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Number Of Orders')),
                ('remaining_orders', models.PositiveIntegerField(default=0, verbose_name='Remaining Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product-images', verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
