# Generated by Django 3.0 on 2020-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image_offer_product_variant_variantoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='products', to='products.VariantOption', verbose_name='Details'),
        ),
    ]
